# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=80)),
                ('numero', models.IntegerField()),
                ('referencia', models.TextField(max_length=150)),
                ('comuna', models.CharField(max_length=80)),
                ('provincia', models.CharField(max_length=80)),
                ('region', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('apellido_paterno', models.CharField(max_length=70)),
                ('apellido_materno', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_movil', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='persona',
            field=models.ForeignKey(blank=True, db_column='rut', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.Persona'),
        ),
    ]
