# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='comuna',
            field=models.ForeignKey(blank=True, db_column='comuna', null=True, on_delete=django.db.models.deletion.CASCADE, to='configurador.Comuna'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='provincia',
            field=models.ForeignKey(blank=True, db_column='provincia', null=True, on_delete=django.db.models.deletion.CASCADE, to='configurador.Provincia'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='configurador.Region'),
        ),
    ]
