# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20160615_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('cantidad_pita_blanco', models.IntegerField()),
                ('cantidad_pita_integral', models.IntegerField()),
                ('cantidad_amasado_blanco', models.IntegerField()),
                ('persona', models.ForeignKey(blank=True, db_column='rut', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.Persona')),
            ],
        ),
    ]
