# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='cantidad_amasado_integral',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
