# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_detalle_cantidad_amasado_integral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='cantidad_amasado_blanco',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='cantidad_amasado_integral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='cantidad_pita_blanco',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='cantidad_pita_integral',
            field=models.IntegerField(default=0),
        ),
    ]
