# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_auto_20160615_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='fecha_pedido',
            field=models.DateField(auto_now_add=True),
        ),
    ]
