# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_auto_20160615_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='inmueble',
            field=models.CharField(choices=[(0, 'Ninguno'), (1, 'Casa'), (2, 'Departamento'), (3, 'Otro')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='fecha_pedido',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
