# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_auto_20160621_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.TextField(max_length=100)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='detalle',
            name='cantidad_panes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalle',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='inmueble',
            field=models.CharField(choices=[('0', 'Ninguno'), ('1', 'Casa'), ('2', 'Departamento'), ('3', 'Otro')], default='0', max_length=2),
        ),
    ]
